# .github/workflows/deploy-to-tencent.yml
name: Deploy to Tencent Cloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Tencent Cloud
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.TENCENT_CLOUD_HOST }}
          username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p /data/proj/tui-xiao-tu
            cd /data/proj/tui-xiao-tu
            
            # Clean up existing files (if any)
            rm -rf * 2>/dev/null || true
            
            # Clone the repository
            # Ensure the directory is empty before cloning
            rm -rf /data/proj/tui-xiao-tu/* /data/proj/tui-xiao-tu/.* 2>/dev/null || true
            git clone https://github.com/${{ github.repository }} .
            
            # Optional: Install dependencies if package.json exists
            if [ -f "package.json" ]; then
              npm install
            fi