# .github/workflows/deploy-to-tencent.yml
name: Deploy to Tencent Cloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Tencent Cloud
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.TENCENT_CLOUD_HOST }}
          username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          script: |
            mkdir -p ~/.ssh
            echo "${{ secrets.TENCENT_CLOUD_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            cd /data/proj/tui-xiao-tu
            rm -rf *
            git clone git@github.com:${{ github.repository }} .