# .github/workflows/deploy-to-tencent.yml
name: Deploy to Tencent Cloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Tencent Cloud
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.TENCENT_CLOUD_HOST }}
          username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p /data/proj/tui-xiao-tu
            cd /data/proj/tui-xiao-tu
            
            # 使用rsync进行增量更新
            rsync -avz --delete --exclude='.git/' ${{ github.workspace }}/ ${{ secrets.TENCENT_CLOUD_USERNAME }}@${{ secrets.TENCENT_CLOUD_HOST }}:/data/proj/tui-xiao-tu
            
            # Optional: Install dependencies if package.json exists
            if [ -f "package.json" ]; then
              npm install
            fi